try {
    4+5
} catch (error) {
    console.log("You messed up", error)
}